// <auto-generated />
using Friendships.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Friendships.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200609012340_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shared.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfirmerEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequesterEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfirmerEmail = "roger@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "pete@fakemail.com"
                        },
                        new
                        {
                            Id = 2,
                            ConfirmerEmail = "john@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "pete@fakemail.com"
                        },
                        new
                        {
                            Id = 3,
                            ConfirmerEmail = "keith@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "pete@fakemail.com"
                        },
                        new
                        {
                            Id = 4,
                            ConfirmerEmail = "john@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "roger@fakemail.com"
                        },
                        new
                        {
                            Id = 5,
                            ConfirmerEmail = "keith@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "roger@fakemail.com"
                        },
                        new
                        {
                            Id = 6,
                            ConfirmerEmail = "john@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "keith@fakemail.com"
                        },
                        new
                        {
                            Id = 7,
                            ConfirmerEmail = "neil@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "geddy@fakemail.com"
                        },
                        new
                        {
                            Id = 8,
                            ConfirmerEmail = "alex@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "geddy@fakemail.com"
                        },
                        new
                        {
                            Id = 9,
                            ConfirmerEmail = "neil@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "alex@fakemail.com"
                        },
                        new
                        {
                            Id = 10,
                            ConfirmerEmail = "freddie@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "jimmi@fakemail.com"
                        },
                        new
                        {
                            Id = 11,
                            ConfirmerEmail = "pete@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "jimmi@fakemail.com"
                        },
                        new
                        {
                            Id = 12,
                            ConfirmerEmail = "geddy@fakemail.com",
                            IsConfirmed = false,
                            RequesterEmail = "jimmi@fakemail.com"
                        },
                        new
                        {
                            Id = 13,
                            ConfirmerEmail = "pete@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "freddie@fakemail.com"
                        },
                        new
                        {
                            Id = 14,
                            ConfirmerEmail = "roger@fakemail.com",
                            IsConfirmed = true,
                            RequesterEmail = "freddie@fakemail.com"
                        },
                        new
                        {
                            Id = 15,
                            ConfirmerEmail = "keith@fakemail.com",
                            IsConfirmed = false,
                            RequesterEmail = "geddy@fakemail.com"
                        },
                        new
                        {
                            Id = 16,
                            ConfirmerEmail = "freddie@fakemail.com",
                            IsConfirmed = false,
                            RequesterEmail = "geddy@fakemail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
