// <auto-generated />
using Images.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Images.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Images.Models.ProfilePhotoPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("ProfilePhotoPaths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "pete@fakemail.com",
                            PhotoPath = "Media/Profiles/pete.png"
                        },
                        new
                        {
                            Id = 2,
                            Email = "roger@fakemail.com",
                            PhotoPath = "Media/Profiles/roger.png"
                        },
                        new
                        {
                            Id = 3,
                            Email = "john@fakemail.com",
                            PhotoPath = "Media/Profiles/john.png"
                        },
                        new
                        {
                            Id = 4,
                            Email = "keith@fakemail.com",
                            PhotoPath = "Media/Profiles/keith.png"
                        },
                        new
                        {
                            Id = 9,
                            Email = "jimmi@fakemail.com",
                            PhotoPath = "Media/Profiles/jimmi.png"
                        },
                        new
                        {
                            Id = 5,
                            Email = "geddy@fakemail.com",
                            PhotoPath = "Media/Profiles/geddy.png"
                        },
                        new
                        {
                            Id = 6,
                            Email = "alex@fakemail.com",
                            PhotoPath = "Media/Profiles/alex.png"
                        },
                        new
                        {
                            Id = 7,
                            Email = "neil@fakemail.com",
                            PhotoPath = "Media/Profiles/neil.png"
                        },
                        new
                        {
                            Id = 8,
                            Email = "freddie@fakemail.com",
                            PhotoPath = "Media/Profiles/freddie.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
